name: CI/CD for React Application

on:
  push:
    branches:
      - main  # Trigger on main branch changes
  pull_request:
    branches:
      - main  # Trigger on main branch changes

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test -- --watchAll=false
      
      - name: Build
        run: npm run build
        env:
          CI: true
      
      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          npm install -g gh-pages
          gh-pages -d build
        env:
          CI: true
